# action.yml
name: 'SSH Command'
description: 'Run a command on a remote server via ssh.'

inputs:
  HOST:
    description: 'hostname / IP of the server'
    required: true
  PORT:
    description: 'ssh port of the server'
    required: false
    default: 22
  USER:
    description: 'user of the server'
    required: true
  PRIVATE_SSH_KEY:
    description: 'private ssh key registered on the server'
    required: true
  COMMAND:
    description: 'command to be executed'
    required: false
    default: 'echo Hello World!'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.HOST }}
    - ${{ inputs.PORT }}
    - ${{ inputs.USER }}
    - ${{ inputs.PRIVATE_SSH_KEY }}
    - ${{ inputs.COMMAND }}

branding:
  icon: 'terminal'
  color: 'yellow'
